//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuckLab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyStock
    {
        public int companyStockId { get; set; }
        public int companyId { get; set; }
        public Nullable<System.DateTime> stockTime { get; set; }
        public Nullable<decimal> stockPrice { get; set; }
        public Nullable<bool> isOpen { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
