//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuckLab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.CompanyStocks = new HashSet<CompanyStock>();
            this.UserStocks = new HashSet<UserStock>();
        }
    
        public int companyID { get; set; }
        public string companyName { get; set; }
        public string companySymbol { get; set; }
    
        public virtual ICollection<CompanyStock> CompanyStocks { get; set; }
        public virtual ICollection<UserStock> UserStocks { get; set; }
    }
}
